FUNCTION(add_modules source)
  IF(UNIX)
    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -std=gnu++0x" PARENT_SCOPE)
  ENDIF()
  INCLUDE_DIRECTORIES(${CMAKE_SOURCE_DIR})
  INCLUDE_DIRECTORIES(include)
  INCLUDE_DIRECTORIES(${common_SOURCE_DIR}/include)
  LIST(LENGTH ARGN len)
  MATH(EXPR len ${len}-1)
  FOREACH(val RANGE ${len})
    LIST(GET ARGN ${val} module)
    LIST(APPEND modules src/${module}.cpp)
    LIST(APPEND modules include/${module}.hpp)
  ENDFOREACH()
  SET(${source} ${modules} PARENT_SCOPE)
ENDFUNCTION(add_modules)
